### ISSUE TITLE
Example format of the valid_mints.json file [Feature]: 

### ISSUE THREAD

**Issue by m4thfr34k** [metaplex-foundation/token-entangler-ui#1]
### Feature

Requesting an example valid_mints.json file.

### Ideal solution or implementation

An example valid_mints.json

### Other context

I've gone through the code and I'm not sure I'm creating a valid valid_mints.json file. Thank you for any assistance you can provide.

**Comment by m4thfr34k** [comment]
I've gone through the code and I'm not sure I'm creating a valid valid_mints.json file. Thank you for any assistance you can provide. @stegaBOB

**Comment by CryptoPique** [comment]
i think it's a simple array:
[
"mint",
"mint"
]

**Comment by m4thfr34k** [comment]
The readme mentions "Also edit the valid_mints.json inside the utils folder to have a list of all valid mints (on both sides of the entanglement)" so I think it's more than a simple array. You need an array of mint pairs, showing that a particular mint address should be entangled with this other specific mint address, but the formats for this that I've tried haven't worked yet.

Have you gotten this to work with a correct valid_mints file?
